language: android

android:
  components:
    - tools
    - platform-tools

    # The SDK version used to compile your project
    - android-26

    # The BuildTools version used by your project
    - build-tools-26.0.2
    
    # Support library
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
